# config.py

# ---------- WELT ----------
TILE_SIZE = 40

WORLD_WIDTH = 80
WORLD_HEIGHT = 60

VISIBLE_WIDTH = 20
VISIBLE_HEIGHT = 15

UI_HEIGHT = 40

WIDTH = VISIBLE_WIDTH * TILE_SIZE
HEIGHT = VISIBLE_HEIGHT * TILE_SIZE + UI_HEIGHT
